### Hi there, I'm Tri Le Minh (aka [ansidev][website]) 👋

<img src="https://komarev.com/ghpvc/?username=ansidev" alt="Profile view" />

#### 📕 About me

- ✝️ I'm a Protestant, developer, blogger, and open-source maintainer & contributor!
- 🇻🇳 My Vietnamese name is Le Minh Tri.
- 🔭 I’m currently working on personal projects!
- 🌱 I’m currently learning English, Go, and front-end stacks!
- 👯 I’m looking to collaborate with other developers building open-source projects for fun and learning!
- 💬 Ask me about everything, however, I'm not sure I will have the answers you need! 😂

#### 👷 Check out what I'm currently working on
{{range recentContributions 5}}
- [{{.Repo.Name}}]({{.Repo.URL}}){{with .Repo.Description}} - {{.}}{{end}} ({{humanize .OccurredAt}})
{{- end}}

#### 🌱 My latest projects
{{range recentRepos 5}}
- [{{.Name}}]({{.URL}}){{with .Description}} - {{.}}{{end}}
{{- end}}

#### 🔭 Latest releases I've contributed to
{{range recentReleases 5}}
- [{{.Name}}]({{.URL}}) ([{{.LastRelease.TagName}}]({{.LastRelease.URL}}), {{humanize .LastRelease.PublishedAt}}){{with .Description}} - {{.}}{{end}}
{{- end}}

#### 🔨 Latest Pull Requests I published
{{range recentPullRequests 5}}
- [{{.Title}}]({{.URL}}) on [{{.Repo.Name}}]({{.Repo.URL}}) ({{humanize .CreatedAt}})
{{- end}}

#### 📜 My recent blog posts

<!-- BLOG-POST-LIST:START --><!-- BLOG-POST-LIST:END -->

#### How to contact me?

[<img align="left" width="32px" src="https://ansidev.xyz/pwa-192x192.png"                alt="ansidev.xyz" style="padding-top: 4px;" />][website]
<a href="mailto:ansidev@gmail.com">
 <img align="left" width="32px" src="https://img.icons8.com/fluency/32/gmail-new.png"    alt="ansidev | Email" />
</a>
[<img align="left" width="32px" src="https://img.icons8.com/fluency/32/github.png"       alt="ansidev | GitHub" />][github]
[<img align="left" width="32px" src="https://img.icons8.com/fluency/32/telegram-app.svg" alt="ansidev | Telegram" />][telegram]
[<img align="left" width="32px" src="https://img.icons8.com/fluency/32/facebook.svg"     alt="ansidev | Facebook" />][facebook]
[<img align="left" width="32px" src="https://img.icons8.com/fluency/32/linkedin.svg"     alt="ansidev | LinkedIn" />][linkedin]
[<img align="left" width="32px" src="https://img.icons8.com/fluency/32/reddit.svg"       alt="ansidev | Reddit" />][reddit]
[<img align="left" width="32px" src="https://img.icons8.com/fluency/32/twitter.svg"      alt="ansidev | Twitter" />][twitter]

<br/>
<br/>

#### How to donate to me?

[<img align="left" height="32px" src="https://www.paypalobjects.com/paypal-ui/logos/svg/paypal-color.svg"  alt="Donate ansidev via Paypal" />][paypal]
[<img align="left" height="32px" src="https://storage.ko-fi.com/cdn/brandasset/kofi_bg_tag_white.png"      alt="Donate ansidev via  Ko-fi" />][kofi]
[<img align="left" height="32px" src="https://cdn.buymeacoffee.com/buttons/v2/default-yellow.png"          alt="Donate ansidev via Buymeacoffee" />][buymeacoffee]
[<img align="left" height="32px" src="https://ansidev.xyz/imgs/momo_icon_rectangle_pinkbg_RGB.png"         alt="Donate ansidev via Momo" />][momo]

<br/>
<br/>

[website]: https://ansidev.xyz/?utm_source=github&utm_medium=readme
[email]: ansidev@gmail.com
[github]: https://github.com/ansidev
[facebook]: https://facebook.com/leminhtri.py
[telegram]: https://t.me/ansidev
[twitter]: https://twitter.com/ansidev
[linkedin]: https://linkedin.com/in/tri-le-minh-1b05bb51/
[reddit]: https://reddit.com/u/ansidev
[paypal]: https://paypal.me/ansidev
[kofi]: https://ko-fi.com/ansidev
[buymeacoffee]: https://buymeacoffee.com/ansidev
[momo]: https://me.momo.vn/ansidev

<br/>
<br/>

<details>
  <summary>My personal GitHub Metrics</summary>
  <br/>
  <img src="./github_metrics_01.svg" />
  <img src="./github_metrics_02.svg" />
</details>

### LICENSE

Please be informed that this project is not released under an open-source license. Therefore, **you don't have permissions to fork/clone/copy it**.

<sub>Auto-generated by [markscribe](https://github.com/muesli/markscribe).</sub>
