name: README
on:
  # Schedule daily updates
  schedule:
    - cron: "0 0 * * *"
  # Run workflow when pushing on master/main
  push:
    branches:
      - main

jobs:
  update_readme:
    name: Update README.md
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch latest GitHub statuses
        uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.MARKSCRIBE_TOKEN }}
        with:
          template: "README.md.tpl"
          writeTo: "README.md"

      - name: Fetch latest blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://ansidev.xyz/feed.rss,https://leetcode.ansidev.xyz/rss.xml"
          max_post_count: 7
