name: README
on:
  # Schedule daily updates
  schedule:
    - cron: "0 0 * * *"
  # Run workflow when pushing on master/main
  push:
    branches:
      - main

jobs:
  update_readme:
    name: Update GitHub status
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch latest GitHub statuses
        uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.MARKSCRIBE_TOKEN }}
        with:
          template: "README.md.tpl"
          writeTo: "README.tmp.md"

      - name: Add blog post list section
        run: |
          sed 's/<blog_post_list \/>/<!-- BLOG-POST-LIST:START --><!-- BLOG-POST-LIST:END -->/g' README.tmp.md > README.md
          rm README.tmp.md

      - name: Fetch latest blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          gh_token: ${{ secrets.GH_TOKEN }}
          feed_list: "https://ansidev.xyz/feed.rss,https://leetcode.ansidev.xyz/rss.xml"
          max_post_count: 7
          enable_keepalive: false
          skip_commit: true

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "build: generate README.md"
          commit_options: "--signoff"
