name: RSS
on:
  # Schedule daily updates
  schedule:
    - cron: "0 0 * * *"
  # Run workflow when pushing on master/main
  push:
    branches:
      - main

jobs:
  update-readme-with-blog:
    name: Latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fetch latest blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://ansidev.xyz/feed.rss,https://leetcode.ansidev.xyz/rss.xml"
          max_post_count: 7
